name: 'Replace Action-Z'
description: 'Replaces substrings in files. Useful to enrich configs with previous steps artifacts.'
author: Data Monsters
branding:
  icon: 'repeat'  
  color: 'green'
inputs:
  files:
    description: 'Files, comma-separated. Supposed PLACEHOLDER in them'
    required: true
  replacements:
    description: 'Comma-separated pairs PLACEHOLDER=value'
    required: true
runs:
  using: 'node20'
  main: 'index.js'
